INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (1,'Hardy','','');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (2,'Lonley','Attack','Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (3,'Brave','Attack','Speed');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (4,'Adamant','Attack','Sp. Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (5,'Naughty','Attack','Sp. Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (6,'Bold','Defense','Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (7,'Docile','','');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (8,'Relaxed','Defense','Speed');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (9,'Impish','Defense','Sp. Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (10,'Lax','Defense','Sp. Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (11,'Timid','Speed','Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (12,'Hasty','Speed','Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (13,'Serious','','');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (14,'Jolly','Speed','Sp. Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (15,'Naive','Speed','Sp. Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (16,'Modest','Sp. Attack','Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (17,'Mild','Sp. Attack','Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (18,'Quiet','Sp. Attack','Speed');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (19,'Bashful','','');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (20,'Rash','Sp. Attack','Sp. Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (21,'Calm','Sp. Defense','Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (22,'Gentle','Sp. Defense','Defense');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (23,'Sassy','Sp. Defense','Speed');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (24,'Careful','Sp. Defense','Sp. Attack');
INSERT INTO `collection_nature` (`id`,`name`,`increase`,`decrease`) VALUES (25,'Quirky','','');