# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'collection', '0001_initial'), (b'collection', '0002_auto_20170707_2255'), (b'collection', '0003_auto_20170707_2308')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type_1', models.CharField(max_length=20)),
                ('type_2', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
