# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type_1', models.CharField(max_length=20)),
                ('type_2', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
