# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170707_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=127)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='region',
            field=models.CharField(choices=[('Kanto', 'Kanto'), ('Johto', 'Johto'), ('Hoenn', 'Hoenn'), ('Sinnoh', 'Sinnoh'), ('Unova', 'Unova'), ('Kalos', 'Kalos'), ('Alola', 'Alola')], default='Kanto', max_length=50),
        ),
    ]
