# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20170707_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='region',
            field=models.CharField(choices=[('Kanto', 'Kanto'), ('Johto', 'Johto'), ('Hoenn', 'Hoenn'), ('Sinnoh', 'Sinnoh'), ('Unova', 'Unova'), ('Kalos', 'Kalos'), ('Alola', 'Alola')], default='Kanto', max_length=50),
        ),
    ]
